spring.application.name=employee-management
server.port=8080
spring.thymeleaf.check-template-location=false
spring.jpa.open-in-view=false

spring.profiles.default=dev

management.endpoints.web.exposure.include=health,metrics

spring.cache.type=caffeine
spring.cache.cache-names=employeeReports
spring.cache.caffeine.spec=expireAfterWrite=60s,maximumSize=100
